[workspace]

members = [
    "aws-mls",
    "aws-mls-core",
    "aws-mls-identity-x509",
    "aws-mls/fuzz",
    "aws-mls/test_harness_integration",
    "aws-mls-crypto-openssl",
    "aws-mls-crypto-rustcrypto",
    "aws-mls-crypto-hpke"
]
