[package]
name = "mls"
version = "0.1.0"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
openssl = "0.10"
