[package]
name = "wickr-bgm"
version = "0.1.1"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2021"

[features]
benchmark = []

[dependencies]
thiserror = "^1"
ferriscrypt = { git = "ssh://git@github.com/WickrInc/ferriscrypt.git", tag = "0.15.0" }
tls_codec = { git = "https://github.com/stephaneyfx/formats.git", branch = "wip" }
tls_codec_derive = { git = "https://github.com/stephaneyfx/formats.git", branch = "wip" }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
hex = "^0.4.2"

[[bench]]
name = "tls"
harness = false
required-features = ["benchmark"]
