[package]
name = "mls"
version = "0.1.0"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
openssl = "0.10"
chacha20poly1305 = "0.7"
x25519-dalek = "1.1"
rand_core = { version = "0.5", default-features = false }
x448 = "0.6"
num = "0.3"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
hex = "0.4.2"
serde_json = "1.0"