[package]
name = "aws-mls"
version = "0.1.1"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2021"

[features]
benchmark = []

[dependencies]
thiserror = "^1"
ferriscrypt = { git = "ssh://git@github.com/WickrInc/ferriscrypt.git", tag = "0.15.1" }
tls_codec = "0.2.0-pre.3"
tls_codec_derive = "0.2.0-pre.3"
hex = { version = "^0.4.3", features = ["serde"] }
enum-iterator = "0.7.0"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.3.5", features = ["html_reports"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

[[bench]]
name = "tls"
harness = false
required-features = ["benchmark"]
