[workspace]

members = [
    "aws-mls",
    "aws-mls-core",
    "aws-mls-identity-x509",
    "aws-mls/fuzz",
    "aws-mls/test_harness_integration",
    "aws-mls/test_utils",
    "aws-mls-crypto-openssl",
    "aws-mls-crypto-rustcrypto",
    "aws-mls-crypto-hpke",
    "aws-mls-provider-sqlite",
    "aws-mls-core/aws-mls-codec",
    "aws-mls-core/aws-mls-codec/derive"
]

default-members = [
    "aws-mls",
    "aws-mls-core",
    "aws-mls-identity-x509",
    "aws-mls-crypto-hpke",
    "aws-mls-crypto-openssl",
    "aws-mls-crypto-rustcrypto",
    "aws-mls-provider-sqlite",
    "aws-mls-core/aws-mls-codec"
]
