[package]
name = "mls"
version = "0.1.0"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1"
ferriscrypt = { git = "ssh://git@github.com/WickrInc/ferriscrypt.git", tag = "0.10.2" }
serde = { version = "^1.0", features = ["derive"] }
bincode = "^1.3"
serde_repr = "^0.1"

[dev-dependencies]
serde_json = "^1.0"
hex = "^0.4.2"

[[test]]
name = "integration"
path = "tests/client_tests.rs"

