[package]
name = "wickr-bgm"
version = "0.1.1"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1"
ferriscrypt = { git = "ssh://git@github.com/WickrInc/ferriscrypt.git", tag = "0.12.1" }
tls_codec = { git = "https://github.com/stephaneyfx/formats.git", branch = "wip" }
tls_codec_derive = { git = "https://github.com/stephaneyfx/formats.git", branch = "wip" }

[dev-dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
hex = "^0.4.2"

