[workspace]
members = ["test_harness_integration"]

[package]
name = "aws-mls"
version = "0.8.0"
authors = ["Tom Leavy <tom@wickr.com>"]
edition = "2021"

[features]
benchmark = []
rustcrypto_engine = ["ferriscrypt/rustcrypto_engine"]
openssl_engine = ["ferriscrypt/openssl_engine"]
browser = ["ferriscrypt/browser", "wasm-bindgen"]
default = ["openssl_engine"]

[dependencies]
thiserror = "^1"
ferriscrypt = { git = "ssh://git@github.com/WickrInc/ferriscrypt.git", default-features = false, features = ["hpke", "serde"], tag = "0.18.1" }
tls_codec = "0.2.0"
tls_codec_derive = "0.2.0"
hex = { version = "^0.4.3", features = ["serde"] }
enum-iterator = "0.8.1"
indexmap = { version = "1.8.0", features = ["serde"] }
der = { version = "^0.5.1", features = ["alloc"]}
serde = { version = "^1.0", features = ["derive"] }
spki = "^0.5.4"
wasm-bindgen = { version = "^0.2.79", optional = true }
zeroize = { version = "^1.3", features = ["zeroize_derive"] }
debug_tree = "0.4.0"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.3.5", features = ["html_reports"] }
serde_json = "^1.0"
rand = "0.8"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3.26", default-features = false }

[[bench]]
name = "encap"
harness = false
required-features = ["benchmark"]

[[bench]]
name = "decap"
harness = false
required-features = ["benchmark"]

[[bench]]
name = "group_serialize"
harness = false
required-features = ["benchmark"]

[[bench]]
name = "group_commit"
harness = false
required-features = ["benchmark"]

[[bench]]
name = "group_application"
harness = false
required-features = ["benchmark"]

[[bench]]
name = "secret_tree_serialize"
harness = false
required-features = ["benchmark"]
