[package]
name = "aws-mls-crypto-traits"
version = "0.2.0"
edition = "2021"

[features]
mock = ["dep:mockall"]

[dependencies]
aws-mls-core = { path = "../aws-mls-core", version = "*" }
mockall = { version = "^0.11", optional = true }
