[package]
name = "aws-mls-core"
version = "0.5.0"
edition = "2021"

[features]
arbitrary = ["dep:arbitrary"]
benchmark = []

[dependencies]
async-trait = "0.1.61"
aws-mls-codec = { version = "*", path = "./aws-mls-codec"}
serde = { version = "1.0", features = ["derive"] }
zeroize = { version = "1", features = ["zeroize_derive"] }
arbitrary = { version = "1", features = ["derive"], optional = true }
serde_with = "2.3.1"
base64 = "0.20.0"
thiserror = "^1"
enum-iterator = "1.1.3"
num_enum = "0.5"
indexmap = { version = "1.8.0", features = ["serde"] }

[dev-dependencies]
assert_matches = "1.5.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3.26", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "^0.2.79" }
