[package]
name = "aws-mls-core"
version = "0.1.0"
edition = "2021"

[features]
arbitrary = ["dep:arbitrary"]
openssl_engine = []
default = ["openssl_engine"]

[dependencies]
tls_codec = "0.2.0"
tls_codec_derive = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
zeroize = { version = "^1.3", features = ["zeroize_derive"] }
arbitrary = { version = "1", features = ["derive"], optional = true }
serde_with = "^2"
base64 = "0.20.0"
thiserror = "^1"
enum-iterator = "1.1.3"
num_enum = "0.5"

[dev-dependencies]
assert_matches = "1.5.0"

