name: Benchmarks on PR
on:
  pull_request:
    branches:
      - main
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::881928689264:role/Github-Actions-Role
          aws-region: us-east-1
      - name: Run benchmark
        working-directory: mls-rs
        run: ( set -o pipefail; cargo bench --features benchmark_util --bench group_commit --bench group_receive_commit --bench group_application --bench group_serialize -- --output-format bencher | tee -a output.txt )
