name: Core
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.FERRIS_DEPLOY }}"
    - name: Rust Fmt
      working-directory: aws-mls-crypto-openssl
      run: cargo fmt --all -- --check
    - name: Clippy
      working-directory: aws-mls-crypto-openssl
      run: cargo clippy -- -D warnings
    - name: Test (OpenSSL Engine)
      working-directory: aws-mls-crypto-openssl
      run: cargo test --verbose
