name: Full Interop Tests
on:
  schedule:
    - cron: '0 5 * * 6'
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        path: mls
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.FERRIS_DEPLOY }}"
    - name: Start test MLS client
      working-directory: test_harness_integration 
      run: cargo run &
    - name: Clone test runner
      uses: actions/checkout@master
      with:
        repository: mulmarta/mls-implementations
        ref: 5a7d4bd59bdc687d6b37ea8062bbb84426de7b0a
        path: interop
    - name: Run tests
      working-directory: interop/interop
      run: |
        python scenario_generators/generate_config_random.py
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN
        GOFLAGS=-mod=mod go generate ./...
        make run-test
