name: Interop Tests
on: [push]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          path: mls
      - name: Clone test runner
        uses: actions/checkout@v4
        with:
          repository: mlswg/mls-implementations
          ref: 3d338d341b1b02c5a2a1a631c60985ce844d2def
          path: interop
      - uses: arduino/setup-protoc@v2
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build test runner
        working-directory: interop/interop
        run: |
          cp -r ../../mls-rs/test_harness_integration/configs mls-rs-configs
          go env -w GOPROXY=direct
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN
          GOFLAGS=-mod=mod go generate ./...
          make test-runner/test-runner
      - name: Test interop; full feature set with itself
        run: |
          cd mls-rs/test_harness_integration
          cargo run -- --port 50001 &
          cd ../../interop/interop
          for config in `ls mls-rs-configs | sed -e "s/mls-rs-configs\///"`; do >&2 echo $config && test-runner/test-runner --client localhost:50001 --config mls-rs-configs/$config ; done > /dev/null
          kill %1
      - name: Test interop; full feature with "bare bones"
        run: |
          cd mls-rs/test_harness_integration
          cargo run -- --port 50001 &
          cargo run --no-default-features -- --port 50002 &
          cd ../../interop/interop
          test-runner/test-runner --client localhost:50001 --client localhost:50002 --suite 1 --public --config mls-rs-configs/bare_bones.json > /dev/null
          kill %1
          kill %2