name: Native
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.FERRIS_DEPLOY }}"
    - name: Rust Fmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings
    - name: Test (OpenSSL Engine) 
      run: cargo test --verbose -- --ignored
    - name: Test (rust crypto engine)
      run: cargo test --verbose --no-default-features --features="rustcrypto_engine"
    - name: Build (Test Harness Integration)
      working-directory: ./test_harness_integration
      run: cargo build
