name: Native
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  BuildAndTest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Rust Fmt
      run: cargo fmt --all -- --check
    - name: Clippy Full RFC Compliance
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings
    - name: Clippy Bare Bones
      run: cargo clippy --all-targets --no-default-features --features std --workspace -- -D warnings
    - name: Test Full RFC Compliance
      run: cargo test --all-features --verbose --workspace
    - name: Test Bare Bones
      run: cargo test --no-default-features --features std --verbose --workspace
    - name: Test Sync Full RFC
      run: RUSTFLAGS='--cfg sync' cargo test --all-features --lib --verbose --workspace 
    - name: Test Sync Bare Bones 
      run: RUSTFLAGS='--cfg sync' cargo test --no-default-features --lib --features std --verbose --workspace
    - name: Examples
      working-directory: aws-mls
      run: cargo run --example basic_usage --features=tokio 
