name: no_std
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: thumbv6m-none-eabi
        components: clippy
    - name: Clippy
      run: cargo +nightly clippy --no-default-features -p aws-mls -- -D warnings
    - name: Test
      run: cargo +nightly test --no-default-features --features test_utils --verbose -p aws-mls
    - name: Test Full RFC Compliance
      run: cargo +nightly test --no-default-features --features rfc_compliant,test_utils --verbose -p aws-mls
    - name: Build MLS Embedded
      run: cargo +nightly build --package aws-mls --lib --no-default-features --target thumbv6m-none-eabi
    - name: Build MLS Embedded Full RFC Compliance
      run: cargo +nightly build --package aws-mls --lib --no-default-features --features rfc_compliant --target thumbv6m-none-eabi
    - name: Build rust crypto embedded 
      run: cargo +nightly build --package aws-mls-crypto-rustcrypto --no-default-features --target thumbv6m-none-eabi
