name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.FERRIS_DEPLOY }}"
    - name: Run tests (openssl engine)
      run: cargo test --verbose -- --ignored
    - name: Run tests (rust crypto engine)
      run: cargo test --verbose --no-default-features --features="rustcrypto_engine"
    - uses: nanasess/setup-chromedriver@v1
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Run tests (web)
      run: wasm-pack test --headless --chrome -- --no-default-features --features="browser"
