name: WASM
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  WASM_BINDGEN_TEST_TIMEOUT: 1000
jobs:
  BuildAndTest:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Setup SSH Keys and known_hosts
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.FERRIS_DEPLOY }}"
    - uses: nanasess/setup-chromedriver@v1
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'v0.10.3'
    - name: Test (WASM + RustCrypto)
      run: wasm-pack test --headless --chrome --release -- --no-default-features --features="browser"
